### PR TITLE
Add Chinese-Simplified translation

### PR DESCRIPTION
**Pull request by WeiguangTWK**
Nice app! Thank you for your FOSS security app.

PS: A string "Pride" is not translated because I didn't find it in app and could not understand what does it actually means. I left it in English

### CODE REVIEW

**Comment by aashishksahu** [comment]
@WeiguangTWK Thank you very much for the translation! About the pride thing, I was thinking of adding a lgbt+ rainbow theme in the month of June, but haven't figured out theming in android yet, lol.

**Comment by aashishksahu** [comment]
@WeiguangTWK I have generated an apk with the translations, please test it and let me know if it is working as intended, I'll then merge it into master. Here's the link : https://github.com/aashishksahu/SafeSpace/blob/chinese-simplified-translation/app/release/app-release.apk

**Comment by WeiguangTWK** [comment]
Screenshot_2023-12-11-16-13-40-347_org privacymatters safespace
Screenshot_2023-12-11-16-13-44-052_org privacymatters safespace
Screenshot_2023-12-11-16-13-46-357_org privacymatters safespace
Screenshot_2023-12-11-16-13-55-220_org privacymatters safespace
Screenshot_2023-12-11-16-13-59-159_org privacymatters safespace
 
It works

**Comment by WeiguangTWK** [comment]
@aashishksahu Screenshot is posted above, it seems that everything is okay

**Comment by aashishksahu** [comment]
@WeiguangTWK ok the, thanks for testing. I'll merge into main soon :)

**Pull request merged**
